version: '3.7'

services:

  memphis-nats:
    image: nats:latest
    container_name: memphis-nats
    ports:
      - 4222:4222
      - 8222:8222
    command: "--store_dir /datastore --jetstream"

  memphis-main-services:
    image: alpine
    container_name: memphis-main-services
    depends_on:
      - memphis-nats
    command: sh -c "echo start"

